"""Public package exports for marimo-3dv."""

try:
    from marimo_3dv._version import __version__
except Exception:
    __version__ = "0.0.0+unknown"

from marimo_3dv.ops.gs import (
    CompiledGsRenderView,
    FilterOpacityConfig,
    FilterSizeConfig,
    GsRenderView,
    MaxShDegreeConfig,
    ShowDistributionConfig,
    SplatLoadConfig,
    SplatLoadGpuConfig,
    SplatRenderData,
    SplatScene,
    cleanup_before_splat_reload,
    compile_gs_render_view,
    filter_opacity_op,
    filter_size_op,
    get_gsplat_device,
    gs_backend_bundle,
    gs_render_view,
    infer_sh_degree,
    load_splat_scene,
    load_splat_scene_from_config,
    max_sh_degree_op,
    pick_splat_load_config,
    show_distribution_op,
    splat_load_form,
)
from marimo_3dv.ops.normalization import (
    apply_rotation_to_quaternions,
    apply_rotation_to_sh_coefficients,
    apply_scale_to_log_scales,
    apply_to_cameras,
    apply_to_points,
    compose_transforms,
    pca_transform_from_points,
    similarity_from_cameras,
)
from marimo_3dv.ops.overlay import PaintRayConfig, paint_ray_op
from marimo_3dv.ops.setup import camera_similarity_op, pca_alignment_op
from marimo_3dv.pipeline.bundle import ViewerBackendBundle, backend_bundle
from marimo_3dv.pipeline.context import ViewerContext
from marimo_3dv.pipeline.gui import (
    AbstractRenderView,
    EffectNode,
    EmptyConfig,
    PipelineGroup,
    RenderNode,
    RenderResult,
    ViewerPipeline,
    ViewerPipelineResult,
    effect_node,
    render_node,
)
from marimo_3dv.pipeline.setup import SetupPipeline
from marimo_3dv.viewer import (
    CameraState,
    CombinedViewerPipelineControlsHandle,
    LinkedViewerStateField,
    MarimoViewer,
    Viewer,
    ViewerCameraConfig,
    ViewerClick,
    ViewerControlsConfig,
    ViewerControlsHandle,
    ViewerInteractionConfig,
    ViewerNavigationConfig,
    ViewerOriginConfig,
    ViewerOverlayConfig,
    ViewerRenderConfig,
    ViewerRotationConfig,
    ViewerState,
    ViewerStateLink,
    ViewerTransformConfig,
    apply_viewer_config,
    apply_viewer_pipeline_config,
    link_viewer_states,
    viewer_controls_config,
    viewer_controls_gui,
    viewer_controls_handle,
    viewer_pipeline_controls_gui,
    viewer_pipeline_controls_handle,
)

__all__ = [
    "AbstractRenderView",
    "CameraState",
    "CombinedViewerPipelineControlsHandle",
    "CompiledGsRenderView",
    "EffectNode",
    "EmptyConfig",
    "FilterOpacityConfig",
    "FilterSizeConfig",
    "GsRenderView",
    "LinkedViewerStateField",
    "MarimoViewer",
    "MaxShDegreeConfig",
    "PaintRayConfig",
    "PipelineGroup",
    "RenderNode",
    "RenderResult",
    "SetupPipeline",
    "ShowDistributionConfig",
    "SplatLoadConfig",
    "SplatLoadGpuConfig",
    "SplatRenderData",
    "SplatScene",
    "Viewer",
    "ViewerBackendBundle",
    "ViewerCameraConfig",
    "ViewerClick",
    "ViewerContext",
    "ViewerControlsConfig",
    "ViewerControlsHandle",
    "ViewerInteractionConfig",
    "ViewerNavigationConfig",
    "ViewerOriginConfig",
    "ViewerOverlayConfig",
    "ViewerPipeline",
    "ViewerPipelineResult",
    "ViewerRenderConfig",
    "ViewerRotationConfig",
    "ViewerState",
    "ViewerStateLink",
    "ViewerTransformConfig",
    "__version__",
    "apply_rotation_to_quaternions",
    "apply_rotation_to_sh_coefficients",
    "apply_scale_to_log_scales",
    "apply_to_cameras",
    "apply_to_points",
    "apply_viewer_config",
    "apply_viewer_pipeline_config",
    "backend_bundle",
    "camera_similarity_op",
    "cleanup_before_splat_reload",
    "compile_gs_render_view",
    "compose_transforms",
    "effect_node",
    "filter_opacity_op",
    "filter_size_op",
    "get_gsplat_device",
    "gs_backend_bundle",
    "gs_render_view",
    "infer_sh_degree",
    "link_viewer_states",
    "load_splat_scene",
    "load_splat_scene_from_config",
    "max_sh_degree_op",
    "paint_ray_op",
    "pca_alignment_op",
    "pca_transform_from_points",
    "pick_splat_load_config",
    "render_node",
    "show_distribution_op",
    "similarity_from_cameras",
    "splat_load_form",
    "viewer_controls_config",
    "viewer_controls_gui",
    "viewer_controls_handle",
    "viewer_pipeline_controls_gui",
    "viewer_pipeline_controls_handle",
]
