"""RADFOAM native backends for Ember."""

from ember_native_radfoam.radfoam import (
    MIN_RADFOAM_POINTS,
    RadFoamAlphaDepthRenderOutput,
    RadFoamNativeRenderOptions,
    RadFoamNativeRenderOutput,
    RadFoamOptimizationRecipe,
    RadFoamTopologyRefresh,
    build_aabb_tree,
    build_radfoam_topology,
    farthest_neighbor,
    initialize_radfoam_model_from_scene_record,
    initialize_radfoam_scene_from_scene_record,
    nearest_neighbor,
    radfoam_farthest_neighbor_radius,
    radfoam_optimization_config,
    radfoam_parameter_groups,
    radfoam_rgb_loss,
    register,
    render_radfoam_native,
    trace,
)
from ember_native_radfoam.registration import register_all

__all__ = [
    "MIN_RADFOAM_POINTS",
    "RadFoamAlphaDepthRenderOutput",
    "RadFoamNativeRenderOptions",
    "RadFoamNativeRenderOutput",
    "RadFoamOptimizationRecipe",
    "RadFoamTopologyRefresh",
    "build_aabb_tree",
    "build_radfoam_topology",
    "farthest_neighbor",
    "initialize_radfoam_model_from_scene_record",
    "initialize_radfoam_scene_from_scene_record",
    "nearest_neighbor",
    "radfoam_farthest_neighbor_radius",
    "radfoam_optimization_config",
    "radfoam_parameter_groups",
    "radfoam_rgb_loss",
    "register",
    "register_all",
    "render_radfoam_native",
    "trace",
]
