"""Ember-native PowerFoam backend."""

from ember_native_powerfoam.powerfoam.renderer import (
    PowerFoamNativeRenderOptions,
    PowerFoamNativeRenderOutput,
    register,
    render_powerfoam_native,
)
from ember_native_powerfoam.powerfoam.runtime import (
    PowerFoamTopology,
    build_powerfoam_topology,
    powerfoam_att_sv,
    powerfoam_camera_from_camera_state,
    powerfoam_density,
    powerfoam_interpenetration,
    powerfoam_normals,
    powerfoam_radii,
    powerfoam_ray_maps,
    powerfoam_tangents,
    powerfoam_texel_world_sites,
    rebuild_powerfoam_topology,
)
from ember_native_powerfoam.powerfoam.training import (
    PowerFoamAdjacencyRefresh,
    PowerFoamOptimizationRecipe,
    PowerFoamResampling,
    initialize_powerfoam_model_from_scene_record,
    initialize_powerfoam_scene_from_scene_record,
    powerfoam_cosine_decay_to,
    powerfoam_optimization_config,
    powerfoam_parameter_groups,
    powerfoam_target_points,
    powerfoam_training_backend_options,
    powerfoam_training_loss,
)

__all__ = [
    "PowerFoamAdjacencyRefresh",
    "PowerFoamNativeRenderOptions",
    "PowerFoamNativeRenderOutput",
    "PowerFoamOptimizationRecipe",
    "PowerFoamResampling",
    "PowerFoamTopology",
    "build_powerfoam_topology",
    "initialize_powerfoam_model_from_scene_record",
    "initialize_powerfoam_scene_from_scene_record",
    "powerfoam_att_sv",
    "powerfoam_camera_from_camera_state",
    "powerfoam_cosine_decay_to",
    "powerfoam_density",
    "powerfoam_interpenetration",
    "powerfoam_normals",
    "powerfoam_optimization_config",
    "powerfoam_parameter_groups",
    "powerfoam_radii",
    "powerfoam_ray_maps",
    "powerfoam_tangents",
    "powerfoam_target_points",
    "powerfoam_texel_world_sites",
    "powerfoam_training_backend_options",
    "powerfoam_training_loss",
    "rebuild_powerfoam_topology",
    "register",
    "render_powerfoam_native",
]
