"""Reusable setup and GUI ops."""

from marimo_3dv.ops.gs import (
    FilterOpacityConfig,
    FilterSizeConfig,
    MaxShDegreeConfig,
    ShowDistributionConfig,
    SplatLoadConfig,
    SplatLoadGpuConfig,
    SplatRenderData,
    SplatScene,
    cleanup_before_splat_reload,
    filter_opacity_op,
    filter_size_op,
    get_gsplat_device,
    infer_sh_degree,
    load_splat_scene,
    load_splat_scene_from_config,
    max_sh_degree_op,
    pick_splat_load_config,
    show_distribution_op,
    splat_load_form,
)
from marimo_3dv.ops.normalization import (
    apply_rotation_to_quaternions,
    apply_rotation_to_sh_coefficients,
    apply_scale_to_log_scales,
    apply_to_cameras,
    apply_to_points,
    compose_transforms,
    pca_transform_from_points,
    similarity_from_cameras,
)
from marimo_3dv.ops.overlay import PaintRayConfig, paint_ray_op
from marimo_3dv.ops.setup import camera_similarity_op, pca_alignment_op

__all__ = [
    "FilterOpacityConfig",
    "FilterSizeConfig",
    "MaxShDegreeConfig",
    "PaintRayConfig",
    "ShowDistributionConfig",
    "SplatLoadConfig",
    "SplatLoadGpuConfig",
    "SplatRenderData",
    "SplatScene",
    "apply_rotation_to_quaternions",
    "apply_rotation_to_sh_coefficients",
    "apply_scale_to_log_scales",
    "apply_to_cameras",
    "apply_to_points",
    "camera_similarity_op",
    "cleanup_before_splat_reload",
    "compose_transforms",
    "filter_opacity_op",
    "filter_size_op",
    "get_gsplat_device",
    "infer_sh_degree",
    "load_splat_scene",
    "load_splat_scene_from_config",
    "max_sh_degree_op",
    "paint_ray_op",
    "pca_alignment_op",
    "pca_transform_from_points",
    "pick_splat_load_config",
    "show_distribution_op",
    "similarity_from_cameras",
    "splat_load_form",
]
